global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: localdev
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:5235


  - job_name: aggregated-trace-metrics
    static_configs:
      - targets:
          - otel-collector:8889

  - job_name: rabbitmq
    static_configs:
      - targets:
          - rabbitmq:15692

  - job_name: postgres-exporter
    static_configs:
      - targets: 
          - postgres-exporter:9187

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: otel-collector
    static_configs:
      - targets:
          - otel-collector:8888

  - job_name: tempo
    static_configs:
      - targets:
          - tempo:3200

  - job_name: jaeger
    static_configs:
      - targets:
          - jaeger:14269

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:9100

  - job_name: docker
    static_configs:
      - targets:
          - docker.for.win.localhost:9323
          # host.docker.internal:9323


  